### ISSUE TITLE
Reuse Classes

### ISSUE THREAD

**Issue by cyouh95** [DanialStoica/f1-3-c2p1-colmar-academy#4]
Instead of creating separate classes for each image, you could apply the same class if the properties are the same. For example, replace `.picture13` and `.picture14` with the same class:

HTML:
```html
<img class="thesis-picture" src="http://i63.tinypic.com/2hx2afd.jpg" alt="picture" />
...
<img class="thesis-picture" src="http://i67.tinypic.com/33ekl02.jpg" alt="picture" />
```

CSS:
```css
.thesis-picture {
  width: 30%;
  height: 157px;
  padding-top: 17.50px;
  padding-right: 24px;
  padding-bottom: 320px;
  padding-left: 20px;
}
```

https://github.com/DanialStoica/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/index.html#L101
https://github.com/DanialStoica/f1-3-c2p1-colmar-academy/blob/master/Colmar%20Academy/index.html#L105
